site_name: Theo Mahl
docs_dir: src
site_dir: docs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  favicon: assets/images/favicon.ico
  name: material
  palette:
    primary: black
